# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.TextField()),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
