# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 18:51
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0002_auto_20160726_1843'),
    ]

    operations = [
        migrations.RunSQL("insert into cwo_structuretype(id,name) value(12242,'Station (Conquerable 1)');"),
        migrations.RunSQL("insert into cwo_structuretype(id,name) value(12294,'Station (Conquerable 2)');"),
        migrations.RunSQL("insert into cwo_structuretype(id,name) value(12295,'Station (Conquerable 3)');"),
        migrations.RunSQL("insert into cwo_structuretype(id,name) value(21642,'Caldari Research Outpost');"),
        migrations.RunSQL("insert into cwo_structuretype(id,name) value(21644,'Amarr Factory Outpost');"),
        migrations.RunSQL("insert into cwo_structuretype(id,name) value(21645,'Gallente Administrative Outpost');"),
        migrations.RunSQL("insert into cwo_structuretype(id,name) value(21646,'Minmatar Service Outpost');"),
        migrations.RunSQL("insert into cwo_structuretype(id,name) value(32226,'Territorial Claim Unit');"),
        migrations.RunSQL("insert into cwo_structuretype(id,name) value(32458,'Infrastructure Hub');")
    ]
