# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0003_auto_20160726_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('alliance_id', models.BigIntegerField()),
                ('defence', models.FloatField()),
                ('structure_id', models.BigIntegerField()),
                ('system_id', models.BigIntegerField()),
                ('type_id', models.BigIntegerField()),
                ('date1', models.DateTimeField()),
                ('date2', models.DateTimeField()),
            ],
        ),
        migrations.RunSQL(
            "CREATE INDEX cwo_structure_structure_id_ind ON cwo_structure (structure_id)",
            "DROP INDEX cwo_structure_structure_id_ind ON cwo_structure"
        ),
        migrations.RunSQL(
            "CREATE INDEX cwo_structure_date1_ind ON cwo_structure (date1)",
            "DROP INDEX cwo_structure_date1_ind ON cwo_structure"
        ),
        migrations.RunSQL(
            "CREATE INDEX cwo_structure_date2_ind ON cwo_structure (date2)",
            "DROP INDEX cwo_structure_date2_ind ON cwo_structure"
        ),
    ]
