# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0003_auto_20160726_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alliance_id', models.BigIntegerField()),
                ('defence', models.FloatField()),
                ('structure_id', models.BigIntegerField()),
                ('system_id', models.BigIntegerField()),
                ('type_id', models.BigIntegerField()),
                ('date1', models.DateTimeField()),
                ('date2', models.DateTimeField()),
            ],
        ),
    ]
