# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0005_alliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='defence',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
