# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0006_auto_20160728_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('war_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantAlliance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_id', models.BigIntegerField()),
                ('alliance_id', models.BigIntegerField()),
                ('date1', models.DateTimeField()),
                ('date2', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('war_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TerritoryRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('territory_id', models.BigIntegerField()),
                ('region_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
