# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0011_auto_20160802_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantalliance',
            name='alliance_id',
        ),
        migrations.RemoveField(
            model_name='participantalliance',
            name='participant_id',
        ),
        migrations.AddField(
            model_name='participantalliance',
            name='alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cwo.Alliance'),
        ),
        migrations.AddField(
            model_name='participantalliance',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cwo.Participant'),
        ),
    ]
