# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0012_auto_20160802_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('system_from_id', models.BigIntegerField()),
                ('system_to_id', models.BigIntegerField()),
            ],
        ),
    ]
