# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0013_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
