# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0014_participant_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='war',
            name='date1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='war',
            name='date2',
            field=models.DateTimeField(null=True),
        ),
    ]
