# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0015_auto_20160804_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='system_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
