# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0016_auto_20160810_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_id', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('event_type', models.CharField(max_length=20)),
                ('defence1', models.DecimalField(decimal_places=1, max_digits=3)),
                ('defence2', models.DecimalField(decimal_places=1, max_digits=3)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwo.Alliance')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwo.System')),
            ],
        ),
        migrations.AlterField(
            model_name='structure',
            name='defence',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
