# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0017_auto_20160812_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='ax',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='ay',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='az',
            field=models.FloatField(null=True),
        ),
    ]
