# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwo', '0018_auto_20160826_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='date1',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='date2',
            field=models.DateTimeField(db_index=True),
        ),
    ]
